### ISSUE TITLE
Print version of Pure Site missing colors

### ISSUE THREAD

**Issue by triptych** [yahoo/pure-site#143]
Not sure if this is even an issue but if you look at the print preview of the pure site the colored bar beneath the "Get Started" button is missing background colors, so the "Base" , "Grids", "Forms", etc look like they are just spaced randomly. 

The same issue is under the "Extend Pure" section where the buttons have no background colors, so just look like words with lots of space between them.

Low priority I'm sure, but looking at the site in "print preview" mode in Chrome reveals things like this.

**Comment by jamesalley** [comment]
Non issue in my opinion. Just check the "print background images" option in your browser's print preview pane and it will look great. Usually that option is not checked by default, but it's necessary if you want your printed page to look like what's on-screen. This problem is common to all websites.
