### ISSUE TITLE
Show me the source

### ISSUE THREAD

**Issue by my2c** [yahoo/pure-site#146]
Hi,
"Get started" button (homepage) goes to "/customize", suggestion for that page: 
1)  add code for minimal page - it will show it's html5, good meta tag(s) and allow quick copy/paste so people can really start.

2) In Layouts - Make footer text(s) "View the source of this layout to learn more" a link or button, or put actual source code there.
Thanks! Good luck!

**Comment by jamesalley** [comment]
When I get questions related to this, it's usually due to people not understanding the scope of Pure, or how much it will do for them. They don't understand the difference between the docs pages, which show Pure in action on its own, and the Layouts (or the site itself), which show Pure being used as a starting point for custom solutions. They expect that they could achieve what they see in the Layouts or Site (e.g.., a sliding menu) with only Pure; they don't understand that they might need to add media queries, custom CSS, some JS, etc. Usually this is not due to the site being poorly written, but due to the user being in a rush, or perhaps the user has very limited understanding of Web development.
