### ISSUE TITLE
Make layout examples more ready to use from a licensing point of view

### ISSUE THREAD

**Issue by ciupicri** [yahoo/pure-site#178]
The [layout examples](http://purecss.io/layouts/) are licensed under BSD, but it's not clear how to comply with it when creating a new page based on them. The HTML and CSS from the examples should have all the necessarily legal texts, so that the user shouldn't worry about being non-complaint.

See also issue #177.

**Comment by gyehuda** [comment]
Users of example text should not have to worry about non-compliance to attribution clauses. We publish examples since we want them to be instructional. BSD is permissive, but we can be even more permissive in this case -- and use the zLib for this code.

The example code is now licensed under the zLib license. The zLib license is like the BSD but does not require attribution. In other words, it does what you were asking, while still being an open source license (granting rights and it has a warranty disclaimer, weak, but it's there).

My apologies for completely dropping the ball on this request. We are cleaning things up now and saw this open.
